version: '3.9'

services:
  frontend:
    build: .
    container_name: frontend 
    ports:
      - "8080:80"
    depends_on:
      - backend
   

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
